export const TIPS: string[] = [
  'Start your day with the hardest task — everything after feels easy.',
  'Break big goals into tiny steps you can finish in one sitting.',
  'A two-minute task is best done right now, not later.',
  'Tidy your desk before you begin; a calm space makes a calm mind.',
  'Write tomorrow\'s top three tasks before you go to bed tonight.',
  'Take a slow breath before starting — focus follows your attention.',
  'Work in 25-minute bursts, then reward yourself with a short break.',
  'Silence your phone and tuck it out of sight while you study.',
  'Done is better than perfect — you can always polish it later.',
  'Drink a glass of water; a hydrated brain thinks far more clearly.',
  'Stretch your legs every hour to keep your energy flowing.',
  'Teach what you learned to someone — explaining locks it in.',
  'Review your notes within a day, and they\'ll stick for weeks.',
  'Stand up, look out a window, and let your eyes rest on something far.',
  'Single-task on purpose; switching between things quietly drains you.',
  'Celebrate small wins — they fuel the momentum for big ones.',
  'When stuck, change your scenery and watch fresh ideas appear.',
  'Sleep is not lazy; it is when your brain files away the day.',
  'Aim for eight hours of rest and wake to a sharper, kinder mind.',
  'Step outside for a few minutes — daylight gently resets your focus.',
  'Eat something green today; your future self will thank you.',
  'Progress over perfection — one small step still moves you forward.',
  'Set a gentle timer and just begin; starting is the hardest part.',
  'Close every tab you don\'t need right now and feel the calm.',
  'Jot down stray thoughts so your mind is free to focus.',
  'Reward deep work with a walk, a snack, or a favorite song.',
  'Plan your breaks on purpose so they refresh instead of distract.',
  'A short nap beats a long slump when your eyes grow heavy.',
  'Keep a water bottle nearby and sip throughout the day.',
  'Move your body for ten minutes — energy makes its own motivation.',
  'Forgive a missed day quickly and simply begin again tomorrow.',
  'Compare yourself to who you were yesterday, no one else.',
  'Say one kind thing to yourself when the work feels heavy.',
  'Protect your mornings for the work that matters most.',
  'Turn off notifications and let yourself disappear into the task.',
  'Read a few pages each day and watch a whole book appear.',
  'Make your goal so small it feels almost silly to skip.',
  'Reflect for a minute tonight on one thing that went well.',
  'Batch similar little tasks together to save your mental energy.',
  'Leave a task slightly unfinished so it\'s easy to dive back in.',
  'Put your study clothes or tools out the night before.',
  'A tidy inbox is a quiet mind — clear it once and breathe.',
  'Trust the boring days; consistency quietly builds something great.',
  'Stand tall and roll your shoulders back to wake up your focus.',
  'Snack on fruit or nuts to keep your thinking steady and bright.',
  'Name the very next action, and the whole project gets lighter.',
  'Give your eyes a break from screens before bed for sweeter sleep.',
  'Keep a "done" list too — it shows how far you\'ve come.',
  'Dim the lights an hour before bed to help your body wind down.',
  'Block out time on your calendar for the work you keep avoiding.',
  'Let yourself be a beginner; every expert fumbled at the start.',
  'A short morning stretch can set a gentle tone for the whole day.',
  'Write your why on a sticky note where you\'ll see it often.',
  'Pause before saying yes; your time is a treasure worth guarding.',
  'Tackle one frog a day and watch the hard things shrink.',
  'Keep healthy snacks within reach and treats a little farther away.',
  'End each work session by noting where you\'ll pick up next.',
  'Breathe in for four counts and out for six to settle your nerves.',
  'Rest is part of the work, not a reward you have to earn.',
  'Show up today, even if just a little — small steps still count.',
  'Curiosity beats willpower; find the fun hiding inside the task.',
  'Put your phone in another room and feel how quiet focus can be.',
]
