import type { Lang } from './i18n'

export const TIPS_EN: string[] = [
  'Start your day with the hardest task — everything after feels easy.',
  'Break big goals into tiny steps you can finish in one sitting.',
  'A two-minute task is best done right now, not later.',
  'Tidy your desk before you begin; a calm space makes a calm mind.',
  "Write tomorrow's top three tasks before you go to bed tonight.",
  'Take a slow breath before starting — focus follows your attention.',
  'Work in 25-minute bursts, then reward yourself with a short break.',
  'Silence your phone and tuck it out of sight while you study.',
  'Done is better than perfect — you can always polish it later.',
  'Drink a glass of water; a hydrated brain thinks far more clearly.',
  'Stretch your legs every hour to keep your energy flowing.',
  'Teach what you learned to someone — explaining locks it in.',
  "Review your notes within a day, and they'll stick for weeks.",
  'Stand up, look out a window, and let your eyes rest on something far.',
  'Single-task on purpose; switching between things quietly drains you.',
  'Celebrate small wins — they fuel the momentum for big ones.',
  'When stuck, change your scenery and watch fresh ideas appear.',
  'Sleep is not lazy; it is when your brain files away the day.',
  'Aim for eight hours of rest and wake to a sharper, kinder mind.',
  'Step outside for a few minutes — daylight gently resets your focus.',
  'Eat something green today; your future self will thank you.',
  'Progress over perfection — one small step still moves you forward.',
  'Set a gentle timer and just begin; starting is the hardest part.',
  "Close every tab you don't need right now and feel the calm.",
  'Jot down stray thoughts so your mind is free to focus.',
  'Reward deep work with a walk, a snack, or a favorite song.',
  'Plan your breaks on purpose so they refresh instead of distract.',
  'A short nap beats a long slump when your eyes grow heavy.',
  'Keep a water bottle nearby and sip throughout the day.',
  'Move your body for ten minutes — energy makes its own motivation.',
  'Forgive a missed day quickly and simply begin again tomorrow.',
  'Compare yourself to who you were yesterday, no one else.',
  'Say one kind thing to yourself when the work feels heavy.',
  'Protect your mornings for the work that matters most.',
  'Turn off notifications and let yourself disappear into the task.',
  'Read a few pages each day and watch a whole book appear.',
  'Make your goal so small it feels almost silly to skip.',
  'Reflect for a minute tonight on one thing that went well.',
  'Batch similar little tasks together to save your mental energy.',
  "Leave a task slightly unfinished so it's easy to dive back in.",
  'Put your study clothes or tools out the night before.',
  'A tidy inbox is a quiet mind — clear it once and breathe.',
  'Trust the boring days; consistency quietly builds something great.',
  'Stand tall and roll your shoulders back to wake up your focus.',
  'Snack on fruit or nuts to keep your thinking steady and bright.',
  'Name the very next action, and the whole project gets lighter.',
  'Give your eyes a break from screens before bed for sweeter sleep.',
  'Keep a "done" list too — it shows how far you\'ve come.',
  'Dim the lights an hour before bed to help your body wind down.',
  'Block out time on your calendar for the work you keep avoiding.',
  'Let yourself be a beginner; every expert fumbled at the start.',
  'A short morning stretch can set a gentle tone for the whole day.',
  "Write your why on a sticky note where you'll see it often.",
  'Pause before saying yes; your time is a treasure worth guarding.',
  'Tackle one frog a day and watch the hard things shrink.',
  'Keep healthy snacks within reach and treats a little farther away.',
  "End each work session by noting where you'll pick up next.",
  'Breathe in for four counts and out for six to settle your nerves.',
  'Rest is part of the work, not a reward you have to earn.',
  'Show up today, even if just a little — small steps still count.',
  'Curiosity beats willpower; find the fun hiding inside the task.',
  'Put your phone in another room and feel how quiet focus can be.',
]

export const TIPS_ZH: string[] = [
  '从最难的任务开始一天——之后的一切都会变得轻松。',
  '把大目标拆成一次就能完成的小步骤。',
  '两分钟能做完的事，现在就做，别拖到以后。',
  '开始前先收拾桌面；环境清爽，心也清爽。',
  '睡前先写下明天最重要的三件事。',
  '开始前慢慢深呼吸——专注会跟着注意力走。',
  '用 25 分钟冲刺，然后给自己一个短暂的休息。',
  '学习时把手机静音，放到看不见的地方。',
  '完成胜过完美——之后随时可以打磨。',
  '喝杯水；大脑补足水分，思路会清晰得多。',
  '每小时活动一下腿脚，让精力流动起来。',
  '把学到的东西讲给别人听——讲明白才算真懂。',
  '一天之内复习笔记，它能记住好几周。',
  '站起来，望向窗外，让眼睛看看远处放松一下。',
  '刻意一次只做一件事；频繁切换会悄悄耗尽你。',
  '庆祝小小的胜利——它们是大胜利的动力。',
  '卡住时换个环境，新点子会自己冒出来。',
  '睡觉不是懒；那是大脑整理一天的时候。',
  '争取睡满八小时，醒来头脑更清醒也更温柔。',
  '出门待几分钟——日光会温柔地重置你的专注。',
  '今天吃点绿色蔬菜，未来的你会感谢现在的你。',
  '进步胜过完美——一小步也是向前。',
  '设个温柔的计时器，直接开始；起步才是最难的。',
  '关掉此刻用不到的所有标签页，感受那份平静。',
  '把闪过的杂念记下来，让大脑腾出空间专注。',
  '用散步、零食或一首爱歌奖励深度工作。',
  '有意安排休息，让它恢复精力，而不是分散注意。',
  '困倦时，小睡片刻胜过长久的萎靡。',
  '把水瓶放在手边，一整天小口补水。',
  '动一动身体十分钟——精力本身就是动力。',
  '错过一天就快快原谅自己，明天重新开始。',
  '和昨天的自己比，而不是和别人比。',
  '工作沉重时，对自己说一句温柔的话。',
  '守护你的早晨，留给最重要的工作。',
  '关掉通知，让自己沉进任务里，消失片刻。',
  '每天读几页，一整本书就会慢慢读完。',
  '把目标定到小得几乎不好意思跳过。',
  '今晚花一分钟，回想一件做得不错的事。',
  '把相似的小任务打包一起做，省下脑力。',
  '任务留一点没做完，下次更容易接上。',
  '前一晚就把学习的衣服或工具准备好。',
  '收件箱清爽，心也安静——清空一次，深呼吸。',
  '相信平淡的日子；坚持会悄悄成就伟大。',
  '抬头挺胸、舒展肩膀，唤醒你的专注。',
  '吃点水果或坚果，让思路稳定又明亮。',
  '想清楚"下一步具体做什么"，整个项目都会变轻。',
  '睡前让眼睛远离屏幕，换来更香的睡眠。',
  '也记一份"已完成"清单——看看自己走了多远。',
  '睡前一小时调暗灯光，帮身体慢慢放松。',
  '在日历上为一直逃避的工作留出时间。',
  '允许自己是新手；每个高手起步时都笨拙过。',
  '早晨简单拉伸，为一整天定个温柔的基调。',
  '把"为什么"写在便利贴上，放在常看见的地方。',
  '答应前先停一停；你的时间是值得守护的珍宝。',
  '每天解决一只"青蛙"，难事会越来越小。',
  '把健康零食放手边，把诱惑放远一点。',
  '每段工作结束时，记下下次从哪里接着做。',
  '吸气四拍、呼气六拍，安抚你的情绪。',
  '休息是工作的一部分，不是要去赚取的奖励。',
  '今天哪怕只做一点点——小步也算数。',
  '好奇胜过意志力；找到任务里藏着的乐趣。',
  '把手机放到另一个房间，感受专注有多安静。',
]

/** The same tip for the whole day, in the chosen language. */
export function dailyTip(lang: Lang): string {
  const arr = lang === 'zh' ? TIPS_ZH : TIPS_EN
  const now = new Date()
  const start = new Date(now.getFullYear(), 0, 0)
  const doy = Math.floor((now.getTime() - start.getTime()) / 86400000)
  return arr[doy % arr.length]
}
